version: 2.1
orbs:
  katalonstudio: katalon-orb-test/katalonstudio@0.0.4

jobs:
  runtest:
    executor: katalonstudio/katalon_orb_executor
    steps:
      - checkout
      - katalon_orb_command

workflows:
  build:
    jobs:
      - runtest
