version: 2.1
orbs:
    katalonstudio: katalon/katalonstudio@14.0.0

environment:
  API_KEY: $API_KEY
workflows:
  build:
    jobs:
        - katalonstudio/test:
                version: "latest"
                COMMAND_ARGUMENTS: '-browserType="Chrome" -retry=1 -statusDelay=16 -testSuitePath="Test Suites/TS_RegressionTest"'
