version: 2.1
orbs:
    katalonstudio: katalon/katalonstudio@19.0.0
environment:
  API_KEY: $API_KEY
workflows:
  build:
    jobs:
        - katalonstudio/run:
                version: "latest"
                katalonstudio/kat_arguments: '-browserType="Chrome" -retry=2 -statusDelay=16 -testSuitePath="Test Suites/TS_RegressionTest"'

