apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.name}}
spec:
  template:
    metadata:
      name: {{.Values.name}}
      labels:
        app: {{.Values.name}}
    spec:
      volumes:
      - name: secrets-volume
        hostPath:
          path: /run/desktop/mnt/host/d/katalon-folder/ci-samples
      containers:
      - name: counter
        image: {{.Values.image}}
#         workingDir: /tmp/project
        volumeMounts:
        - name: www-data
          mountPath: /tmp/project
#           readOnly: true
        command: ["/bin/sh"]
#         args: ["-c","ls /tmp/project"]
        args: ["-c","katalonc.sh -projectPath=/tmp/project -browserType='Chrome' -testSuiteCollectionPath='Test Suites/TS_RegressionTestCollection' -apiKey='555232dc-21e0-4567-8bd9-a7335fa67975'"]
#         command:
#          - "bin/bash"
#          - "-c"
#          - "katalonc.sh -projectPath=$(pwd) -browserType='Chrome' -testSuiteCollectionPath='Test Suites/TS_RegressionTestCollection' -apiKey='555232dc-21e0-4567-8bd9-a7335fa67975'"
      initContainers:
      - name: git-cloner
        image: alpine/git
        args:
            - clone
            - --single-branch
            - --
            - https://github.com/HieuBui419/ci-samples.git
            - /data
        volumeMounts:
        - mountPath: /data
          name: www-data
      volumes:
      - name: www-data
        emptyDir: {}
      restartPolicy: Never
