apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.name}}
spec:
  template:
    metadata:
      name: {{.Values.name}}
      labels:
        app: {{.Values.name}}
    spec:
      volumes:
      - name: secrets-volume
        hostPath:
          path: /host_mnt/d/katalon-folder/ci-samples
      containers:
      - name: counter
        image: {{.Values.image}}
#         workingDir: /tmp/project
        volumeMounts:
        - name: secrets-volume
          mountPath: /tmp/project
          readOnly: true
        command: ["/bin/sh"]
        args: ["-c","katalonc.sh -projectPath=/tmp/project -browserType='Chrome' -testSuiteCollectionPath='Test Suites/TS_RegressionTestCollection' -apiKey='555232dc-21e0-4567-8bd9-a7335fa67975'"]
#         command:
#          - "bin/bash"
#          - "-c"
#          - "katalonc.sh -projectPath=$(pwd) -browserType='Chrome' -testSuiteCollectionPath='Test Suites/TS_RegressionTestCollection' -apiKey='555232dc-21e0-4567-8bd9-a7335fa67975'"
      restartPolicy: Never
